In [26]:
import pandas as pd

# se crea el objeto df al leer el dataset en csv
df = pd.read_csv("dataset_crudo.csv")
# mostramos las 5 primeras filas
df.head(5)

,id_venta,nombre_apellido,provincia,metodo_envio,medio_pago,producto,marca,categoria,cantidad,precio_unitario,subtotal,descuento_porcentaje,descuento,TOTAL,categoria_venta,fecha_compra,fecha_entrega,demora_entrega
0,352,Carlos Martínez,Córdoba,Envío estándar,Efectivo,PRO H610M-G DDR4,Geil,Placas Madre,10,"$ 772,00","$ 7.720,00",0%,"$ 0,00","$ 7.720,00",Bajo,1/1/2024,6/1/2024,5.0
1,913,Paula Pérez,Neuquén,Envío express,Mercado Pago,Core i9-14900K,Intel,Procesadores,20,"$ 56.005,00","$ 1.120.100,00",15%,"$ 168.015,00","$ 952.085,00",Alto,1/1/2024,6/1/2024,5.0
2,10,Luis Ruiz,Buenos Aires,Retiro en tienda,Mercado Pago,600 W1 600W 80+ White,EVGA,Fuentes de Poder,20,"$ 6.382,00","$ 127.640,00",10%,"$ 12.764,00","$ 114.876,00",Bajo,1/1/2024,7/1/2024,6.0
3,389,Andrés García,Buenos Aires,Envío express,Efectivo,Crucial DDR4 8GB 2666MHz,Crucial,Memorias RAM,20,"$ 2.629,00","$ 52.580,00",0%,"$ 0,00","$ 52.580,00",Bajo,1/1/2024,7/1/2024,6.0
4,1287,Luis Gómez,Buenos Aires,Envío estándar,Efectivo,Ryzen 5 5600X,AMD,Procesadores,20,"$ 14.885,00","$ 297.700,00",10%,"$ 29.770,00","$ 267.930,00",Bajo,2/1/2024,8/1/2024,6.0

In [36]:
# verificamos las dimensiones del dataset con shape
print(f"Dimensiones del dataset: {df.shape}")
print("\nResumen del dataser con info():\n")
df.info()

Dimensiones del dataset: (1503, 18)

Resumen del dataser con info():

<class 'pandas.core.frame.DataFrame'>
Index: 1503 entries, 0 to 1504
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_venta              1503 non-null   int64
 1   nombre_apellido       1503 non-null   object
 2   provincia             1503 non-null   object
 3   metodo_envio          1503 non-null   object
 4   medio_pago            1503 non-null   object
 5   producto              1503 non-null   object
 6   marca                 1503 non-null   object
 7   categoria             1503 non-null   object
 8   cantidad              1503 non-null   int64
 9   precio_unitario       1503 non-null   float64
 10  subtotal              1503 non-null   float64
 11  descuento_porcentaje  1502 non-null   float64
 12  descuento             1503 non-null   float64
 13  TOTAL                 1503 non-null   float64
 14  categoria_venta       1503 non-null   object
 15  fecha_compra          1503 non-null   object
 16  fecha_entrega         1503 non-null   object
 17  demora_entrega        1503 non-null   float64
dtypes: float64(6), int64(2), object(10)
memory usage: 223.1+ KB

In [28]:
print("--- VALORES NULOS POR COLUMNA ---")

# calculamos la cantidad de nulos en cada columna
nulos_cant = df.isnull().sum()
# calculamos el porcentaje de nulos en cada columna
nulos_pct = df.isnull().mean() * 100

# creamos el DataFrame resumen
df_nulos = pd.DataFrame({
    'Cantidad': nulos_cant,
    'Porcentaje(%)': nulos_pct.round(3)
})

# filtramos solo las columnas con nulos mayores a 0
display(df_nulos[df_nulos['Cantidad'] > 0])

--- VALORES NULOS POR COLUMNA ---

                      Cantidad  Porcentaje(%)
provincia                    1          0.066
medio_pago                   1          0.066
descuento_porcentaje         1          0.066
descuento                    1          0.066
fecha_entrega                1          0.066
demora_entrega               1          0.066

In [29]:
# filtramos y mostramos todas las filas que contienen al menos un valor nulo
registros_con_nulos = df[df.isnull().any(axis=1)]

print(f"Se encontraron {len(registros_con_nulos)} registros con valores nulos:")
display(registros_con_nulos)

Se encontraron 3 registros con valores nulos:

,id_venta,nombre_apellido,provincia,metodo_envio,medio_pago,producto,marca,categoria,cantidad,precio_unitario,subtotal,descuento_porcentaje,descuento,TOTAL,categoria_venta,fecha_compra,fecha_entrega,demora_entrega
1500,1501,Juan Pérez,NaN,Envío estándar,NaN,Ryzen 5 5600X,AMD,Procesadores,1,"$ 14.885,00","$ 14.885,00",0%,"$ 0,00","$ 14.885,00",Bajo,15/09/2024,20/09/2024,5.0
1502,1503,María Gómez,Córdoba,Envío estándar,Tarjeta Crédito,PRO H610M-G DDR4,Geil,Placas Madre,10,"$ 772,00","$ 7.720,00",0%,"$ 0,00","$ 7.720,00",Bajo,17/09/2024,NaN,NaN
1504,1505,Laura Rossi,Santa Fe,Retiro en tienda,Efectivo,Blue SN580 NVMe 500GB,Western Digital,Almacenamiento,10,"$ 4.383,00","$ 43.830,00",NaN,NaN,"$ 43.830,00",Bajo,20/09/2024,22/09/2024,2.0

In [30]:
# borramos los dos registros que contienen 2 nulos cada uno
df = df.drop([1500, 1502])


# para 'descuento_porcentaje' y 'descuento' reemplazamos los nulos por 0
df['descuento_porcentaje'] = df['descuento_porcentaje'].fillna(0)
df['descuento'] = df['descuento'].fillna(0)

# verificamos que ya no queden valores nulos en el df
print("--- Cantidad de nulos después de la imputación ---")
display(df.isnull().sum())

--- Cantidad de nulos después de la imputación ---

id_venta                0
nombre_apellido         0
provincia               0
metodo_envio            0
medio_pago              0
producto                0
marca                   0
categoria               0
cantidad                0
precio_unitario         0
subtotal                0
descuento_porcentaje    0
descuento               0
TOTAL                   0
categoria_venta         0
fecha_compra            0
fecha_entrega           0
demora_entrega          0
dtype: int64

In [31]:
print("--- ESTADISTICAS DESCRIPTIVAS ---")
df.describe()

--- ESTADISTICAS DESCRIPTIVAS ---

          id_venta     cantidad  demora_entrega
count  1503.000000  1503.000000     1503.000000
mean    752.003327    20.765136        4.039255
std     434.028802    14.858859        2.899410
min       1.000000    10.000000        1.000000
25%     376.500000    10.000000        2.000000
50%     752.000000    20.000000        4.000000
75%    1127.500000    30.000000        6.000000
max    1505.000000   500.000000       85.000000

In [32]:
def buscar_outliers(df, columna):
  """
      esta funcion recibe un dataframe de pandas y una columna
      para devolver un dataframe con los outliers encontrados
  """
  q1 = df[columna].quantile(0.25)
  q3 = df[columna].quantile(0.75)
  iqr = q3 - q1
  outliers_cantidad1 = df[df[columna] > (q3 + 1.5 * iqr)]
  outliers_cantidad2 = df[df[columna] < (q1 - 1.5 * iqr)]
  outliers_cantidad = pd.concat([outliers_cantidad1, outliers_cantidad2])
  if outliers_cantidad.empty:
      return None
  else:
      return outliers_cantidad

# mostramos los outliers en la columna cantidad
outliers_cantidad = buscar_outliers(df, 'cantidad')
if outliers_cantidad is not None:
  print("\n--- OUTLIERS EN CANTIDAD ---")
  print(outliers_cantidad[['id_venta', 'nombre_apellido', 'producto', 'cantidad']])

# mostramos los outliers en la columna cantidad
outliers_demora = buscar_outliers(df, 'demora_entrega')
if outliers_demora is not None:
  print("\n--- OUTLIERS EN DEMORA DE ENTREGA ---")
  print(outliers_demora[['id_venta', 'nombre_apellido', 'provincia', 'demora_entrega']])

--- OUTLIERS EN CANTIDAD ---
      id_venta   nombre_apellido                  producto  cantidad
1501      1502  Empresa Tech SRL  Crucial DDR4 8GB 2666MHz       500

--- OUTLIERS EN DEMORA DE ENTREGA ---
      id_venta    nombre_apellido provincia  demora_entrega
1503      1504  Roberto Fernández   Mendoza            85.0

In [33]:
# CONVERSION DE COLUMNAS
# decidi crear una funcion para normalizar las columnas que contienen precios
# de esta forma voy a tener preparado el DataFrame para mas adelante hacer calculos numericos

def normalizar_precios(columna):
  """
  Recibe una columna y la normaliza a float64 de forma segura,
  preservando y respetando los valores nulos (NaN) nativos.
  """
  # trabajamos solo con las filas que no sean nulas para aplicar el reemplazo de texto
  filas_no_nulas = df[columna].notna()

  # convertimos a string y limpiamos solo los valores existentes
  valores_limpios = df.loc[filas_no_nulas, columna].astype(str)
  valores_limpios = valores_limpios.str.replace('$', '', regex=False).str.strip()
  valores_limpios = valores_limpios.str.replace('.', '', regex=False)
  valores_limpios = valores_limpios.str.replace(',', '.', regex=False)

  # convertimos a float usando pd.to_numeric para mayor seguridad
  df.loc[filas_no_nulas, columna] = pd.to_numeric(valores_limpios, errors='coerce')

  # aseguramos que toda la columna sea float64 en el DataFrame
  df[columna] = df[columna].astype(float)

In [34]:
# aplicamos la función normalizar_precios a las columnas monetarias
columnas_monetarias = ['precio_unitario', 'subtotal', 'descuento', 'TOTAL']

for col in columnas_monetarias:
    normalizar_precios(col)

display(df[columnas_monetarias].info())
display(df[columnas_monetarias].head())

<class 'pandas.core.frame.DataFrame'>
Index: 1503 entries, 0 to 1504
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   precio_unitario  1503 non-null   float64
 1   subtotal         1503 non-null   float64
 2   descuento        1503 non-null   float64
 3   TOTAL            1503 non-null   float64
dtypes: float64(4)
memory usage: 58.7 KB

None

   precio_unitario   subtotal  descuento     TOTAL
0            772.0     7720.0        0.0    7720.0
1          56005.0  1120100.0   168015.0  952085.0
2           6382.0   127640.0    12764.0  114876.0
3           2629.0    52580.0        0.0   52580.0
4          14885.0   297700.0    29770.0  267930.0

In [35]:
# convertimos a numerica la columna de descuento_porcentaje
df['descuento_porcentaje'] = df['descuento_porcentaje'].str.rstrip('%').astype(float) / 100
df['descuento_porcentaje'] = df['descuento_porcentaje'].round(2)
display(df['descuento_porcentaje'].head())

0    0.00
1    0.15
2    0.10
3    0.00
4    0.10
Name: descuento_porcentaje, dtype: float64

In [37]:
# verificamos la cantidad de ventas por marca
ventas_por_marca = df.groupby('marca').size().reset_index(name='cantidad_ventas')

# ordenamos el resultado por la cantidad_ventas
ventas_por_marca = ventas_por_marca.sort_values(by='cantidad_ventas', ascending=False)

print("--- Ventas por marca  ---")
display(ventas_por_marca)

--- Ventas por marca  ---

              marca  cantidad_ventas
0               AMD              340
10           NVIDIA              196
8             Intel              184
3           Corsair              152
2     Cooler Master               86
1              ASUS               83
12      Thermaltake               83
6              Geil               73
9          Kingston               73
13  Western Digital               67
7          Gigabyte               55
4           Crucial               51
5              EVGA               37
11          Seagate               23

In [40]:
ventas_por_categoria = df.groupby('categoria')['id_venta'].count().reset_index(name='cantidad_ventas')

ventas_por_categoria = ventas_por_categoria.sort_values(by='cantidad_ventas', ascending=False)

print("--- Ventas por categoria  ---")
display(ventas_por_categoria)

--- Ventas por categoria  ---

           categoria  cantidad_ventas
5       Procesadores              385
7  Tarjetas de Video              345
0     Almacenamiento              143
4       Placas Madre              138
2          Gabinetes              128
3       Memorias RAM              123
6      Refrigeración              122
1   Fuentes de Poder              119

In [39]:
# total por provincia
total_por_provincia = df.groupby('provincia')['TOTAL'].sum().reset_index(name='total_ventas')

# ordenamos el resultado por el total_ventas
total_por_provincia = total_por_provincia.sort_values(by='total_ventas', ascending=False)

print("--- Total por provincia  ---")
display(total_por_provincia)

--- Total por provincia  ---

      provincia  total_ventas
0  Buenos Aires   208741873.0
5      Santa Fe   144831276.5
2       Mendoza    84284277.0
1       Córdoba    75932978.0
3       Neuquén    75802561.0
6       Tucumán    75098770.5
4         Salta    69369716.0